#define FUNCTION_INFINITE_AMMO 100
#define FUNCTION_RAPID_FIRE 101
#define FUNCTION_NO_SPREAD 102
#define FUNCTION_NO_RECOIL 103
#define FUNCTION_FIELD_OF_VIEW 104
#define FUNCTION_WALLHACK 105
#define FUNCTION_CHAMS 106

#define FUNCTION_LVL_UP 200
#define FUNCTION_CUSTOM_NAME 201
#define FUNCTION_DOUBLE_XP 202

#define FUNCTION_SUPER_SPEED 300
#define FUNCTION_RESPAWN 301
#define FUNCTION_MOVEMENT_ALWAYS_ALLOWED 302
#define FUNCTION_FIRING_ALWAYS_ALLOWED 303

#define FUNCTION_LEVEL_UP 400
#define FUNCTION_LEVEL_DOWN 401
#define FUNCTION_ADD_MONEY 402
#define FUNCTION_ALWAYS_HOLD_BOMB 403
#define FUNCTION_PLANT_ANYWHERE 404
#define FUNCTION_DEFUSE_ANYWHERE 405

#define FUNCTION_RESPAWN_BEFORE_DIE 500
#define FUNCTION_SPAM_CHAT 501
#define FUNCTION_JUMP_EXPLOIT 502
#define FUNCTION_TELEKILL 503
#define FUNCTION_AIMBOT 504
#define FUNCTION_WALKING_NUKE 505

void toggleButton(int id) {

}